<h2>Basics</h2>

In [1]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In [2]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [4]:
x = [3, 4, 5]
x

[3, 4, 5]

In [5]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

<h2>Numerical Python</h2>
<p>Mostly working with numpy</p>

In [6]:
import numpy as np

In [7]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])
x + y

array([ 7, 13, 12])

<h3>Important: vector VS matrix</h3>
<ul>
    <li>vector: 1 dimensional array</li>
    <li>matrix: 2 dimensional array</li>
</ul>

In [10]:
#matrix
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

<h3>Array attribute examples</h3>

In [12]:
x.ndim

2

In [17]:
y = np.array([[1,2, 4], [3, 4, 2], [5, 6, 9]])
y

array([[1, 2, 4],
       [3, 4, 2],
       [5, 6, 9]])

In [18]:
y.ndim

2

In [19]:
x.dtype

dtype('int64')

In [20]:
y.dtype

dtype('int64')

In [21]:
z = np.array([[1, 2], [3.5, 4]])
z.dtype

dtype('float64')

In [22]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [24]:
a = np.array([[1,2],[3,4]], float)

In [25]:
a.dtype

dtype('float64')

<h3>Array methods examples</h3>

In [27]:
x = np.array([1,2,3,4])
x.sum()

10

In [29]:
# transforming a vector into an array consists of 2 rows & 3 cols
x = np.array([1, 2, 3, 4, 5, 6])
x_reshape = x.reshape(2,3)
x_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
x.mean()

3.5

In [33]:
x = np.array([[1,2],[3,4], [7,8]], float)
x.mean()

4.166666666666667

In [34]:
x.min()

1.0

<h4>Index array element</h4>

In [35]:
x[0,0]

1.0

In [37]:
x[2,1]

8.0

In [38]:
x = np.array([1, 2, 3, 4, 5, 6])
x_reshape = x.reshape(2,3)
x_reshape[0,0] = 5
x_reshape

array([[5, 2, 3],
       [4, 5, 6]])

In [39]:
x_reshape.shape

(2, 3)

In [40]:
x_reshape.ndim

2

In [44]:
x_reshape.T

array([[5, 4],
       [2, 5],
       [3, 6]])

<h4>perform math on array</h4>

In [46]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [47]:
x**2

array([25,  4,  9, 16, 25, 36])

In [48]:
x*0.5

array([2.5, 1. , 1.5, 2. , 2.5, 3. ])

<h4>use np to generate random data</h4>

In [50]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [49]:
x = np.random.normal(size=50)
x

array([-0.2681141 , -0.10989881, -0.80226625,  0.40112319, -1.09688081,
       -1.18263946,  1.34235005,  0.69072343,  1.14877632, -1.12781278,
       -0.49480492,  1.4460232 ,  2.93020417, -0.08915093,  0.88119747,
        0.55061247, -1.14175493,  1.64816538, -0.59852081,  0.05170706,
        0.41075719, -1.85235843,  0.32341101, -2.02370527,  0.00901148,
       -2.01528919,  0.79302794,  0.39611741, -0.42184338,  0.40904002,
       -0.10616702, -1.51362702, -0.477481  , -0.84758862, -0.34745743,
       -0.13474465, -0.99289918,  0.85805906,  0.07800654,  1.49857983,
        0.198759  , -1.50309414,  0.5987884 ,  0.65627686,  0.1225379 ,
        2.76844714, -1.6229456 , -0.44439009,  1.67820988,  0.49892451])

In [51]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([50.6254941 , 49.88466946, 47.6147224 , 50.58626738, 52.01204534,
       47.46384484, 52.01816198, 51.37668442, 53.17399565, 49.5924167 ,
       48.70263975, 52.66632077, 51.22682729, 48.62837743, 51.24020376,
       50.92282769, 48.20584217, 51.67140612, 50.45923224, 50.63527626,
       52.06107466, 48.30878494, 50.77492328, 47.94512113, 48.06625697,
       45.03075766, 49.89000818, 49.47408318, 49.90046434, 49.99622873,
       49.75458565, 48.72885276, 47.97343756, 48.68957251, 50.5406874 ,
       49.8308488 , 50.34844105, 50.67352894, 48.90970631, 51.74393833,
       49.86800975, 47.03491064, 51.82899831, 51.07091491, 49.63669623,
       51.41375128, 49.44438301, 48.62957783, 52.90959582, 50.21689725])

In [52]:
np.corrcoef(x,y)

array([[1.       , 0.7295891],
       [0.7295891, 1.       ]])

In [54]:
np.random.default_rng?

Docstring:
default_rng(seed=None)
Construct a new Generator with the default BitGenerator (PCG64).

    Parameters
    ----------
    seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator}, optional
        A seed to initialize the `BitGenerator`. If None, then fresh,
        unpredictable entropy will be pulled from the OS. If an ``int`` or
        ``array_like[ints]`` is passed, then it will be passed to
        `SeedSequence` to derive the initial `BitGenerator` state. One may also
        pass in a `SeedSequence` instance.
        Additionally, when passed a `BitGenerator`, it will be wrapped by
        `Generator`. If passed a `Generator`, it will be returned unaltered.

    Returns
    -------
    Generator
        The initialized generator object.

    Notes
    -----
    If ``seed`` is not a `BitGenerator` or a `Generator`, a new `BitGenerator`
    is instantiated. This function does not manage a default global instance.

    See :ref:`seeding_and_entropy` 

In [56]:
rng = np.random.default_rng(1303)
x = rng.normal(scale=5, size=2)
rng1 = np.random.default_rng(1303)
y =rng1.normal(scale=5, size=2)

In [57]:
x

array([ 4.09482632, -1.07485605])

In [58]:
y

array([ 4.09482632, -1.07485605])

<h2>Data Viz</h2>