# Numerical Python

In [5]:
import numpy as np

*Numy is a multi-dimensional array library*

In [2]:
x = np.array([3, 4, 5])
y = np.array([6, 7, 8])
x + y

array([ 9, 11, 13])

*vector*: one-dimensional array<br>
*matrix*: two-dimmensional array



In [4]:
# matrix example: 
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
x.ndim

2

In [11]:
x.dtype

dtype('int64')

In [12]:
np.array([[1.5, 3],[2.2, 6]]).dtype

dtype('float64')

In [13]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [14]:
x.shape

(2, 2)

In [15]:
x = np.array([1, 3, 5, 9])
np.sum(x)

18

In [18]:
## python reshape 
x = np.array([1, 2, 3, 4, 5, 6])
x_reshape = x.reshape((2, 3))
x

array([1, 2, 3, 4, 5, 6])

In [20]:
x_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#indexing into numpy
x_reshape[0, 0]

1

In [23]:
x[2]

3

In [24]:
x_reshape[0, 0] = 10
x_reshape

array([[10,  2,  3],
       [ 4,  5,  6]])

In [25]:
x

array([10,  2,  3,  4,  5,  6])

In [27]:
#common array attribute: shape, ndim & T
x_reshape.shape

(2, 3)

In [28]:
x_reshape.ndim

2

In [29]:
x_reshape.T

array([[10,  4],
       [ 2,  5],
       [ 3,  6]])