# Lab

## Intro to Numeric Python

In [1]:
import numpy as np

In [2]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [3]:
x + y 

array([ 7, 13, 12])

In [4]:
x = np.array([
    [1, 2],
    [3, 4]
])
x 

array([[1, 2],
       [3, 4]])

### sample of array attributes

In [6]:
x.ndim

2

In [7]:
x.dtype

dtype('int64')

In [9]:
x.shape

(2, 2)

### Reshape array

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
print(f'beginning x:\n {x}')
x_reshape = x.reshape((2, 3))
print(f'reshaped x:\n {x_reshape}')

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]
