# Lab

## Intro to Numeric Python

In [1]:
import numpy as np

In [2]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [3]:
x + y 

array([ 7, 13, 12])

In [4]:
x = np.array([
    [1, 2],
    [3, 4]
])
x 

array([[1, 2],
       [3, 4]])

### sample of array attributes

In [6]:
x.ndim

2

In [7]:
x.dtype

dtype('int64')

In [9]:
x.shape

(2, 2)

### Reshape array

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
print(f'beginning x:\n {x}')
x_reshape = x.reshape((2, 3))
print(f'reshaped x:\n {x_reshape}')

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [18]:
print(f'x before any modification:\n {x}')
print()

print(f'x before any reshaping:\n {x_reshape}')
print()

x_reshape[0, 0] = 10
print(f'x_reshape after modifying its top left element:\n {x_reshape}')
print()

print(f'x after modifying x_reshape top left element:\n {x}')

x before any modification:
 [10  2  3  4  5  6]

x before any reshaping:
 [[10  2  3]
 [ 4  5  6]]

x_reshape after modifying its top left element:
 [[10  2  3]
 [ 4  5  6]]

x after modifying x_reshape top left element:
 [10  2  3  4  5  6]


## Math operations on array

In [19]:
np.sqrt(x)

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [20]:
x**2

array([100,   4,   9,  16,  25,  36])

In [21]:
x**0.5

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

## Generate random data

In [22]:
x = np.random.normal(size=50)
x

array([ 1.06208891, -1.63805122, -1.27879451,  0.4869308 , -0.0463668 ,
        0.88239615, -0.23275321,  0.82200468,  0.5933236 ,  0.70324816,
       -1.81077387, -1.16708443,  0.39495251, -0.08890768,  0.01660451,
       -1.13495658, -0.94310032, -0.6790851 ,  0.05395769,  1.13156768,
       -0.85127197, -0.02161334,  0.07754419,  1.30044108, -0.43111571,
        0.97348545, -0.26228512, -0.70558426,  0.31581832,  2.16887786,
       -1.67947304,  0.52946932, -0.51751568,  1.33844951,  0.49447329,
        0.46232836,  0.37119237,  0.19143129,  1.85316826, -1.68302167,
       -1.82183196,  0.05011767,  1.00110786,  2.39626823, -1.07746386,
       -1.01035025, -0.53704454, -0.27136551, -0.07790509, -0.79271485])

In [24]:
y = x + np.random.normal(50, 1, 50)
y

array([49.14624715, 48.40204804, 49.0968941 , 49.12122196, 48.36760646,
       50.3922745 , 51.85046929, 50.48707159, 49.71544677, 48.3617647 ,
       48.20507205, 48.57551763, 50.73324563, 51.91150745, 49.42047731,
       47.86716517, 48.08836892, 47.91157065, 50.77302748, 52.21998883,
       50.15418626, 50.83076386, 50.85082297, 50.95386724, 49.28842693,
       50.93011904, 49.1487293 , 49.92788901, 49.67928338, 52.29096656,
       47.72994266, 48.58412598, 49.02230603, 52.10788059, 50.27967171,
       50.76067488, 50.71328625, 48.91627735, 50.19285142, 48.58803578,
       48.67363378, 50.38326673, 50.26376658, 51.90845055, 50.86915459,
       49.23593648, 49.70916743, 50.70553557, 50.51328115, 47.60406147])

In [25]:
np.corrcoef(x, y)

array([[1.        , 0.63348934],
       [0.63348934, 1.        ]])