In [1]:
import numpy as np

## Chapter 2 exercises

### 2.4 Compute the following matrix products, if possible:

In [12]:
#a 
a = np.array([[1, 2],
              [4, 5],
              [7,8]])
b = np.array([[1, 1, 0],
              [0, 1, 1],
              [1, 0, 1]
])
np.matmul(a, b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [16]:
#b 
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[1, 1, 0],
              [0, 1, 1],
              [1, 0, 1]])
np.matmul(a, b)

array([[ 4,  3,  5],
       [10,  9, 11],
       [16, 15, 17]])

In [17]:
#c
np.matmul(b,a)

array([[ 5,  7,  9],
       [11, 13, 15],
       [ 8, 10, 12]])

In [18]:
#d 
a = np.array([[1, 2, 1, 2],
              [4, 1, -1, -4]])
b = np.array([[0, 3],
              [1, -1],
              [2, 1],
              [5, 2]])
np.matmul(a,b)

array([[ 14,   6],
       [-21,   2]])

In [19]:
#e 
np.matmul(b,a)

array([[ 12,   3,  -3, -12],
       [ -3,   1,   2,   6],
       [  6,   5,   1,   0],
       [ 13,  12,   3,   2]])