In [1]:
import numpy as np


# Conceptual Ideas

## 2.2.2 Inverse and Transpose

In [2]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])

In [3]:
B = np.linalg.inv(A)
B

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In [4]:
np.matmul(A, B)

array([[ 1.00000000e+00, -1.77635684e-15,  8.88178420e-16],
       [-2.22044605e-15,  1.00000000e+00,  4.44089210e-15],
       [ 7.54951657e-15, -1.77635684e-15,  1.00000000e+00]])

**Take away:** \
Matrix x Inversed_matrix = identify matrix \
transpose means: row becomes column & column becomes row

### important properties of inverses and transposes & Proof

In [5]:
a = np.array([[1, 2, 3],
              [4, 4, 5],
              [5, 8, 9]])
b = np.array([[1, 1, 0],
              [0, 1, 1],
              [1, 0, 1]])

$(AB)^{-1}$ = $B^{-1}A^{-1}$

In [6]:
a_inverse = np.linalg.inv(a)
b_inverse = np.linalg.inv(b)
a_and_b_inverse = np.linalg.inv(np.matmul(a, b))

In [7]:
a_and_b_inverse

array([[ 0.95,  0.7 , -0.65],
       [-1.35, -0.1 ,  0.45],
       [ 0.25, -0.5 ,  0.25]])

In [8]:
np.matmul(b_inverse, a_inverse)

array([[ 0.95,  0.7 , -0.65],
       [-1.35, -0.1 ,  0.45],
       [ 0.25, -0.5 ,  0.25]])

$(A+B)^{-1} \neq A^{-1}+B^{-1}$

In [9]:
a_and_b = np.add(a, b)
a_and_b

array([[ 2,  3,  3],
       [ 4,  5,  6],
       [ 6,  8, 10]])

In [10]:
a_and_b_inverse = np.linalg.inv(a_and_b)
a_and_b_inverse

array([[-1.00000000e+00,  3.00000000e+00, -1.50000000e+00],
       [ 2.00000000e+00, -1.00000000e+00, -3.33066907e-16],
       [-1.00000000e+00, -1.00000000e+00,  1.00000000e+00]])

In [11]:
np.add(a_inverse, b_inverse)

array([[ 0.1,  0.1,  0.3],
       [-0.6, -0.1,  0.2],
       [ 0.7,  0.7,  0.1]])

$(A^{T})^{T} = A $

In [12]:
a_transpose = a.transpose()

In [13]:
a

array([[1, 2, 3],
       [4, 4, 5],
       [5, 8, 9]])

In [14]:
a_transpose

array([[1, 4, 5],
       [2, 4, 8],
       [3, 5, 9]])

In [15]:
a_transpose.transpose()

array([[1, 2, 3],
       [4, 4, 5],
       [5, 8, 9]])

$(AB)^{T} = B^{T}A^{T}$

In [16]:
a_transpose = a.transpose()
b_transpose = b.transpose()

In [17]:
a_and_b_transpose = np.matmul(a,b).transpose()
a_and_b_transpose

array([[ 4,  9, 14],
       [ 3,  8, 13],
       [ 5,  9, 17]])

In [18]:
np.matmul(b_transpose, a_transpose)

array([[ 4,  9, 14],
       [ 3,  8, 13],
       [ 5,  9, 17]])

$(A+B)^{T} = A^{T} + B^{T}$

In [19]:
a_and_b = np.add(a,b)
a_and_b_transpose = a_and_b.transpose()

In [20]:
a_and_b

array([[ 2,  3,  3],
       [ 4,  5,  6],
       [ 6,  8, 10]])

In [21]:
a_and_b_transpose

array([[ 2,  4,  6],
       [ 3,  5,  8],
       [ 3,  6, 10]])

In [22]:
np.add(a.transpose(), b.transpose())

array([[ 2,  4,  6],
       [ 3,  5,  8],
       [ 3,  6, 10]])

### 2.4.1 Groups

1. Closure of G under ⊗: ∀x, y ∈ G : x ⊗ y ∈ G \
&emsp;&emsp;For all x, y under the set G, the output of x+y or x*y is the under the set G 
2. Associativity: ∀x, y, z ∈ G : (x ⊗ y) ⊗ z = x ⊗ (y ⊗ z) \
&emsp;&emsp;for x, y, z under the set G, (x+y)+(z)==x+(y+x), (xy)z==x(yz)
3. Neutral element: ∃e ∈ G ∀x ∈ G : x ⊗ e = x and e ⊗ x = x \
&emsp;&emsp;There exist a 'e" where x+e=e and x*e=x
4. Inverse element: ∀x ∈ G ∃y ∈ G : x ⊗ y = e and y ⊗ x = e, where e is the neutral element. We often write $x^{−1}$ to denote the inverse element of x. \
&emsp;&emsp;For x under the set G, there exist y where xy = e 

## Selected exercises

### 2.1 consider (R\{−1}, ⋆), where a ⋆ b := ab + a + b, a, b ∈ R\{−1} 
**a. Show that (R\{−1}, ⋆) is an Abelian group** \
&emsp;&emsp;Note: operation a*b should never produce -1 \
&emsp;&emsp;Since a\*b$\neq$-1, we can rewrite the operation as a ⋆ b := ab + a + b + 1 where a$\neq$-1 and b$\neq$-1

**Abelian group criteria** \
1. Closure:\
&emsp;&emsp;a, b ∈ R \
&emsp;&emsp;ab + a + b + 1  ∈ R \
&emsp;&emsp;Closure condition met 
2. Neutral element: \
&emsp;&emsp;Neutral element=0
4. Associatiity: \
&emsp;&emsp;a, b, c ∈ R \
&emsp;&emsp;(ab + a + b) + c = ab + (a + b + c) \
&emsp;&emsp;Associativity condition met 
5. Neutral/Identity element: \
&emsp;&emsp; ab + a + b + 0 = ab + a + b \
&emsp;&emsp; Neutral element condition met  
6. Inverse element: inverse condition met 
7. a⋆b=ab+a+b=ba+b+a=b⋆a \
&emsp;&emsp;Commutative condition met \
thus it's an Abelian group


### 2.4 Compute the following matrix products, if possible:

In [23]:
#a there's no solution

In [24]:
#b 
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[1, 1, 0],
              [0, 1, 1],
              [1, 0, 1]])
np.matmul(a, b)

array([[ 4,  3,  5],
       [10,  9, 11],
       [16, 15, 17]])

In [25]:
#c
np.matmul(b,a)

array([[ 5,  7,  9],
       [11, 13, 15],
       [ 8, 10, 12]])

In [26]:
#d 
a = np.array([[1, 2, 1, 2],
              [4, 1, -1, -4]])
b = np.array([[0, 3],
              [1, -1],
              [2, 1],
              [5, 2]])
np.matmul(a,b)

array([[ 14,   6],
       [-21,   2]])

In [27]:
#e 
np.matmul(b,a)

array([[ 12,   3,  -3, -12],
       [ -3,   1,   2,   6],
       [  6,   5,   1,   0],
       [ 13,  12,   3,   2]])

### 2.5 Find the set S of all solutions in x of the following inhomogeneous linear systems Ax = b, where A and b are defined as follows:

In [28]:
#a, no solution 
A = np.array([[1, 1, -1, -1],
     [2, 5, -7, -5],
     [2, -1, 1, 3],
     [5, 2, -4, 2]])
B = np.array([1, -2, 4, 6])


In [29]:
#b: infinitely many solutions
A = np.array([[1, -1, 0, 0, 1],
              [1, 1, 0, -3, 0],
              [2, -1, 0, 1, -1], 
              [-1, 2, 0, -2, -1]])
B = np.array([3, 6, 5, -1])


### 2.6 Using Gaussian elimination, find all solutions of the inhomogeneous equation system Ax = b


In [30]:
A = np.array([[0, 1, 0, 0, 1, 0], 
              [0, 0, 0, 1, 1, 0], 
              [0, 1, 0, 0, 0, 1]])
B = np.array([2, -1, 1])


### 2.8 Find inverse matrix

In [31]:
a = np.array([[1, 0, 1, 0],
              [0, 1, 1, 0],
              [1, 1, 0, 1],
              [1, 1, 1, 0]])
np.linalg.inv(a)

array([[ 0., -1.,  0.,  1.],
       [-1.,  0.,  0.,  1.],
       [ 1.,  1., -0., -1.],
       [ 1.,  1.,  1., -2.]])