<h2>Numerical python, such as numpy package, etc</h2>

In [1]:
import numpy as np

In [2]:
x = np.array([4, 9, 2])
y = np.array([3, 1, 7])

In [3]:
x + y

array([ 7, 10,  9])

<h3>Two dimensional array, aka matrices, example below</h3>

In [17]:
a = np.array([[2, 4, 1], [5, 9, 7]])
a

array([[2, 4, 1],
       [5, 9, 7]])

<h3>One dimensional array, aka ventor, example below <h3>

In [18]:
b = np.array([7, 9])
b

array([7, 9])

<h3>array attribute</h3>

In [19]:
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [20]:
print(a.shape)

(2, 3)


In [21]:
print(a.strides)

(24, 8)


In [22]:
print(a.ndim)

2


In [23]:
print(a.size)

6


In [24]:
print(a.dtype)

int64
