In [1]:
import numpy as np

In [2]:
# represent row vector
rowVector = np.array([[1, 2, 3, 4, 5]])
print(rowVector)

[[1 2 3 4 5]]


In [3]:
# represent column vector
colVector = np.array([[1], [2], [3], [4], [5]])
print(colVector)

[[1]
 [2]
 [3]
 [4]
 [5]]


<h1>1. Vector arithmatic</h1>
<p>Addition, subtraction, multiplication & division can only be performed on vectors of the same dimensions</p>

In [4]:
a = np.array([24, 50, 89])
b = np.array([21, 10, 8])
c = np.array([34, 70, 9, 67])

In [5]:
a+b

array([45, 60, 97])

In [6]:
a-b

array([ 3, 40, 81])

In [7]:
a*b

array([504, 500, 712])

In [8]:
a/b

array([ 1.14285714,  5.        , 11.125     ])

<h3>Scalar multiplication</h3>

In [9]:
scalar = 2

In [10]:
scalar * a

array([ 48, 100, 178])

In [11]:
scalar * b


array([42, 20, 16])

In [12]:
scalar * c

array([ 68, 140,  18, 134])

<h1>2.Dot product of vectors</h1>

In [13]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [14]:
np.dot(a, b)

130

<h3>Dot product is commutative</h3>
<pre>
    a * b = b * a
</pre>
<p>example below</p>

In [16]:
#np.dot(a, b) == np.dot(b, a)
np.dot(b, a)

130

<h3>Dot product is distributive</h3>
<pre>
    a(b+c) = a*b + a*c
</pre>

In [17]:
c = np.array([11, 12, 13, 14, 15])

In [18]:
np.dot(a, b+c)

335

In [19]:
np.dot(a,b)+np.dot(a,c)

335