In [1]:
import numpy as np

In [2]:
# represent row vector
rowVector = np.array([[1, 2, 3, 4, 5]])
print(rowVector)

[[1 2 3 4 5]]


In [4]:
# represent column vector
colVector = np.array([[1], [2], [3], [4], [5]])
print(colVector)

[[1]
 [2]
 [3]
 [4]
 [5]]


<h1>Vector arithmatic</h1>
<p>Addition, subtraction, multiplication & division can only be performed on vectors of the same dimensions</p>

In [7]:
a = np.array([24, 50, 89])
b = np.array([21, 10, 8])
c = np.array([34, 70, 9, 67])

In [8]:
a+b

array([45, 60, 97])

In [10]:
a-b

array([ 3, 40, 81])

In [12]:
a*b

array([504, 500, 712])

In [13]:
a/b

array([ 1.14285714,  5.        , 11.125     ])

<h2>Scalar multiplication</h2>

In [14]:
scalar = 2

In [15]:
scalar * a

array([ 48, 100, 178])

In [16]:
scalar * b


array([42, 20, 16])

In [17]:
scalar * c

array([ 68, 140,  18, 134])